name: My cool and WORKING CI/CD pipeline using Terraform and Docker containers

on:
    workflow_dispatch:
    push:
        branches:
            - "main"

env:
    fe_image_name: "youtube-video-assignment-fe"
    be_image_name: "youtube-video-assignment-be"

jobs:
    build_and_push_fe:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v5

            - name: Get the Git commit
              run: |
                  VERSION=$(git rev-parse --short HEAD)
                  echo "COMMIT_VERSION=$VERSION" >> $GITHUB_ENV

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: ./ecommerce-app-frontend
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{env.fe_image_name}}:latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{env.fe_image_name}}:${{env.COMMIT_VERSION}}
    build_and_push_be:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v5

            - name: Get the Git commit
              run: |
                  VERSION=$(git rev-parse --short HEAD)
                  echo "COMMIT_VERSION=$VERSION" >> $GITHUB_ENV

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  context: ./ecommerce-app-frontend
                  tags: |
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{env.be_image_name}}:latest
                      ${{ secrets.DOCKERHUB_USERNAME }}/${{env.be_image_name}}:${{env.COMMIT_VERSION}}

    provision_with_terraform:
        runs-on: ubuntu-latest
        needs: [build_and_push_be, build_and_push_fe]
        env:
            my_name: ${{secrets.NAME}}
            subscription_id: ${{secrets.subscription_id}}
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v5

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Azure Login
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Change to Terraform directory
              run: cd terraform

            - name: Terraform initialize
              run: terraform init

            - name: Terraform apply
              run: terraform apply
